Support for OSTREE-based distributions
bayasdev/envycontrol pull request #181
Opened 2024-08-11 05:21 UTC by PilotGuy772

This addresses #180. 

EnvyControl is configured right now to put udev rules in `/lib/udev`. The problem with this is that `/lib/udev` is distinctly intended for udev rules from the distribution. It is NOT meant to be manipulated so heavily. Instead, system admins ought to use `/etc/udev` to put custom rules. 

This ordinarily isn't a problem for EnvyControl because most distros don't care if you modify `/lib/`, but immutable distros like Fedora Silverblue *do* care. `/lib/` is not writable, but `/etc/` is. There's a reason for that.

This PR **changes the udev directory to `/etc/udev/`**, but everything still works as expected with this change. I also added logic to check if the distribution uses ostree by checking for `/ostree` and `/sysroot/ostree`, which are the two places where you would usually find the ostree directory. My amateur testing on Bluefin has shown that switching between integrated and hybrid modes works perfectly.

2024-08-11 17:03 UTC, bayasdev requested changes

2024-08-11 17:03 UTC, bayasdev commented on envycontrol.py
> +UDEV_INTEGRATED_PATH = '/etc/udev/rules.d/50-remove-nvidia.rules'
@PilotGuy772 could you please add a new variable instead? As systems running older versions may have these files on their previous location the cleanup routine will not remove them

2024-08-11 17:03 UTC, bayasdev commented on envycontrol.py
> +UDEV_PM_PATH = '/etc/udev/rules.d/80-nvidia-pm.rules'
Same here

2024-08-11 17:07 UTC, bayasdev commented on envycontrol.py
> +UDEV_INTEGRATED_PATH = '/etc/udev/rules.d/50-remove-nvidia.rules'
Another solution would be to manually add the paths to the cleanup routine that way we won't need a new variable

2024-08-12 01:00 UTC, PilotGuy772 commented
@bayasdev I added logic to cleanup() in my latest commit to address your concerns. I just have statements to check for EnvyControl's udev rules in `/lib/udev/rules.d` and remove them if they exist.

2024-08-12 02:38 UTC, bayasdev requested changes

2024-08-12 02:38 UTC, bayasdev commented on envycontrol.py
> +    if os.path.exists(legacy_udev):
@PilotGuy772 I think we could do something like this instead

```
    # define list of files to remove
    to_remove = [
        BLACKLIST_PATH,
        UDEV_INTEGRATED_PATH,
        UDEV_PM_PATH,
        XORG_PATH,
        EXTRA_XORG_PATH,
        MODESET_PATH,
        LIGHTDM_SCRIPT_PATH,
        LIGHTDM_CONFIG_PATH,
        # legacy paths
        '/etc/X11/xorg.conf.d/90-nvidia.conf',
        '/lib/udev/rules.d/50-remove-nvidia.rules',
        '/lib/udev/rules.d/80-nvidia-pm.rules'
    ]

    # remove each file in the list
    for file_path in to_remove:
        try:
            if os.path.exists(lfile_path):
                os.remove(file_path)
                logging.info(f"Removed file {file_path}")
        except OSError as e:
            # only warn if file exists (code 2)
            if e.errno != 2:
                logging.error(f"Failed to remove file '{file_path}': {e}")
```

2024-08-12 02:38 UTC, bayasdev commented on envycontrol.py
> +        # this takes a LLOOOOOONG time to run, so let's warn the user first.
could you please remove the redundant comments?

2024-08-12 02:38 UTC, bayasdev commented on envycontrol.py
> +        self.current_mode = get_nvidia_gpu_pci_bus()
why was this changed?

2024-08-12 02:40 UTC, bayasdev commented
@PilotGuy772 please take a look at the comments I left, and thank you for adding OSTree support to EnvyControl as it was a frequently requested feature 🙌🏼

2024-08-14 18:43 UTC, PilotGuy772 commented
@bayasdev All done (I think)

2024-08-14 18:53 UTC, bayasdev approved these changes
LGTM

2024-08-14 18:53 UTC, merged

2024-08-14 18:53 UTC, bayasdev commented
Thanks @PilotGuy772